#pragma once
#define GAME_VERSION 2
//#define DEV_MODE
#define CLIENT_WIDTH 1024
#define CLIENT_HEIGHT 768
#define GAME_WIDTH 768
#define GAME_HEIGHT 768
#define BRICK_WIDTH 48
#define BRICK_HEIGHT 16
#define BAT_WIDTH 64
#define BAT_HEIGHT 16

#define BALL_DIMENSION 16
#define POWERUP_DIMENSION 32
#define POWERUP_ICON 16
#define TARGET_FPS 144.f
//Microseconds / FPS
#define TARGET_FRAMES ((1000.f * 1000.f) / TARGET_FPS)
#define PANEL_WIDTH (CLIENT_WIDTH - GAME_WIDTH)
#define GRID_COLUMNS (GAME_WIDTH / BRICK_WIDTH)
#define GRID_ROWS (GAME_HEIGHT / BRICK_HEIGHT)
#define BAT_Y (GRID_ROWS - 2) * BRICK_HEIGHT
#define BALL_START_Y (GRID_ROWS - 4) * BRICK_HEIGHT
#define DEFAULT_CAMPAIGN L"main"
#define MAP_DIRECTORY L"assets\\levels\\"
#define POWERUP_SPRITE L"powerup"
#define STAR_SPRITE L"star"
#define HYPERBALL_SPRITE L"hyperball"
#define BARRIER_SPRITE L"barrier"
#define NOPOINT_SPRITE L"nopoint"
#define LASERBAT_SPRITE L"laserbat"
#define EDITOR_BUTTONS_PER_PAGE 16
#define EDITOR_BUTTON_HEIGHT 36
#define EDITOR_BUTTON_WIDTH 110
#define HIGHSCORE_SIZE 10

#define MAX_LIVES 6